---
- name: install multi-packages
  hosts: all
  tasks:
    - name: git, tree  and curl
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - tree
        - curl

